# Generated by Django 4.2.7 on 2025-09-21 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('change_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prompt',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveIndex(
            model_name='prompt',
            name='prompts_pro_title_3ccf03_idx',
        ),
        migrations.RemoveIndex(
            model_name='prompt',
            name='prompts_pro_categor_81e06d_idx',
        ),
        migrations.RemoveIndex(
            model_name='prompt',
            name='prompts_pro_author__acb3fd_idx',
        ),
        migrations.AddField(
            model_name='prompt',
            name='current_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='prompt',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to='prompts.category'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promptversion',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promptversion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prompts.category'),
        ),
        migrations.AddField(
            model_name='promptversion',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='prompts.prompt'),
        ),
        migrations.AlterUniqueTogether(
            name='promptversion',
            unique_together={('prompt', 'version_number')},
        ),
    ]
