# Generated by Django 4.2.7 on 2025-09-21 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prompts', '0002_promptversion_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('LOGIN_FAILED', 'Failed Login Attempt'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET', 'Password Reset'), ('USER_CREATE', 'User Created'), ('USER_UPDATE', 'User Updated'), ('USER_DELETE', 'User Deleted'), ('PERMISSION_CHANGE', 'Permission Changed'), ('PROMPT_CREATE', 'Prompt Created'), ('PROMPT_UPDATE', 'Prompt Updated'), ('PROMPT_DELETE', 'Prompt Deleted'), ('PROMPT_VIEW', 'Prompt Viewed'), ('PROMPT_USE', 'Prompt Used'), ('CATEGORY_CREATE', 'Category Created'), ('CATEGORY_UPDATE', 'Category Updated'), ('CATEGORY_DELETE', 'Category Deleted'), ('AI_SUGGESTION', 'AI Suggestion Generated'), ('AI_IMPROVEMENT', 'AI Improvement Applied'), ('AI_ANALYSIS', 'AI Analysis Performed'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity Detected'), ('RATE_LIMIT_EXCEEDED', 'Rate Limit Exceeded'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access Attempt'), ('DATA_EXPORT', 'Data Export')], max_length=50)),
                ('resource_type', models.CharField(blank=True, max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='prompts_aud_user_id_859ca7_idx'), models.Index(fields=['action', '-timestamp'], name='prompts_aud_action_ea2f64_idx'), models.Index(fields=['resource_type', 'resource_id', '-timestamp'], name='prompts_aud_resourc_5f5da4_idx'), models.Index(fields=['timestamp'], name='prompts_aud_timesta_12a313_idx')],
            },
        ),
    ]
