# Generated by Django 4.2.7 on 2025-09-21 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prompts', '0003_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardrailsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('config_type', models.CharField(choices=[('input_validation', 'Input Validation'), ('output_moderation', 'Output Moderation'), ('conversation_control', 'Conversation Control'), ('content_filtering', 'Content Filtering'), ('custom_rules', 'Custom Rules')], max_length=50)),
                ('configuration', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardrails_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuardrailsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('input_validation', 'Input Validation'), ('output_moderation', 'Output Moderation'), ('conversation_moderation', 'Conversation Moderation'), ('jailbreak_attempt', 'Jailbreak Attempt'), ('content_violation', 'Content Violation'), ('rate_limit', 'Rate Limit Exceeded')], max_length=50)),
                ('log_level', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('allowed', models.BooleanField(default=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardrails_logs', to='prompts.prompt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardrails_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='prompts_gua_user_id_ceae5a_idx'), models.Index(fields=['action_type', '-timestamp'], name='prompts_gua_action__8154e2_idx'), models.Index(fields=['log_level', '-timestamp'], name='prompts_gua_log_lev_7da707_idx'), models.Index(fields=['timestamp'], name='prompts_gua_timesta_eda7e7_idx')],
            },
        ),
    ]
